# Generated by Django 6.1.1 on 2026-09-15 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eligibility_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.company')),
            ],
        ),
    ]
